ads_project:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: ""
      user: ""
      role: "{{ env_var('DBT_ROLE') }}"
      database: "{{ env_var('DBT_DATABASE') }}"
      warehouse: "{{ env_var('DBT_WAREHOUSE') }}"
      schema: ADS
      threads: 4
    qa:
      type: snowflake
      account: ""
      user: ""
      role: "{{ env_var('DBT_ROLE') }}"
      database: "{{ env_var('DBT_DATABASE') }}"
      warehouse: "{{ env_var('DBT_WAREHOUSE') }}"
      schema: ADS
      threads: 4